### ISSUE TITLE
Huge saving failure

### ISSUE THREAD

**Issue by ghost** [meeech/Shopify-Theme-Tool-Public#14] opened 2012-06-15 19:29 UTC
So, this just happened: http://cl.ly/HOsK

It's a screen-cap of what happened when I tried to save my Shopify CSS file; a repeated popup message scrawled across my screen of the save's failure. These cleared to be replaced immediately by another 30 or so identical popups. It was pretty freaky! :)

This occurred after simply starting up Shopify Theme, opening my CSS file to make changes, and then hitting "save". I'll try deleting and re-adding the theme to S.T. and see if it happens again.

**Comment by ghost** [comment] 2012-06-15 19:34
Follow-up: http://cl.ly/HQPj  <--- UPDATED LINK, WORKS CORRECTLY NOW

**Comment by meeech** [comment] 2012-06-15 19:43
hey luc - followup seems not right image.

Not sure whats happening there - looks like its appending something to the file name. What editor you using?

**Comment by ghost** [comment] 2012-06-15 20:00
I had to remove the store from S.T. altogether, and re-add it, but it took a few tries. It initially wasn't recognizing the shop because I still had it temporarily closed with "Storefront Password." When I removed that, I could add the shop again. This is odd because it wasn't a problem the first time around. Maybe Shopify changed stuff this weekend?

**Comment by ghost** [comment] 2012-06-15 20:03
Sorry about the bad link! Here's the correct one: http://cl.ly/HQPj

I'm using CSSEdit, from MacRabbit. Same one I was using the past couple of weeks.

**Comment by meeech** [comment] 2012-06-16 11:30
Thanks Luc. I'll check with them to see if something has changed. Because the storefront password shouldnt affect it (beyond viewing the store)

**Comment by meeech** [comment] 2012-06-25 00:15
Gonna close this one - haven't been able to reproduce or discover cause. Please reopen (or open a new ticket) if you experience this again.

**Closed as completed by meeech** 2012-06-25 00:15 UTC
