### ISSUE TITLE
Doesn't complete first sync

### ISSUE THREAD

**Issue by stewartjohnson** [meeech/Shopify-Theme-Tool-Public#8] opened 2012-02-21 02:15 UTC
1. Start app.
2. Enter store name.
3. Press 'Add Shop'
4. Presented with list of themes.
5. Select my main theme.
6. Select directory
7. download starts
8. downloads approx 1.5M of files into selected directory
9. gets to assets/tw-widget.js and hangs, Activity Monitor shows no network activity, browsing web/email works fine
10. 10 mins later no progress

**Comment by stewartjohnson** [comment] 2012-02-21 02:17
Note that the file tw-widget.js is successfully downloaded (it's in the download directory).

**Comment by meeech** [comment] 2012-02-21 03:24
It strange that its not timing out at the very least. Any chance you could share this theme with me, so i can test against it?

**Comment by stewartjohnson** [comment] 2012-02-21 03:58
It's a purchased theme, and the licence says I can't share the code (it's from Shopaholla).

**Comment by stewartjohnson** [comment] 2012-02-21 03:58
Lemme blow everything away and try again.

**Comment by stewartjohnson** [comment] 2012-02-21 04:22
Well, there you go. It worked this time. I've just made some edits using macvim and they were synced to my site just fine. I guess you can close this bug for now.

**Comment by stewartjohnson** [comment] 2012-02-21 09:15
I tried it again downloading to a different location, and it failed again (got stuck on the same file). I blew everything away and tried it again in the same location (/home/stewart/dev/) and it failed on the same file.

Unfortunately I can't figure out what's causing it to fail.

**Comment by meeech** [comment] 2012-02-22 01:56
hey stewart - Can you launch Console.app (should be in /Applications/Utilities) and try again. There should be some output from the app which may help narrow down the issue. Here's an example of what you will see:  ![screenshot](http://imgur.com/ZHGP5.png) You can just select the rows in that window, CMD-C and paste it into a text file to send to me. (mitchell.amihod@gmail.com)

**Comment by stewartjohnson** [comment] 2012-02-22 04:11
22/02/12 3:09:46.069 PM [0x0-0x5cb5cb].com.meeech.shopify_theme2: [04:09:46:068] [Titanium.API] [Information] PUT: Success
22/02/12 3:09:46.929 PM [0x0-0x5cb5cb].com.meeech.shopify_theme2: [04:09:46:928] [Titanium.API] [Information] PUT: Success
22/02/12 3:09:48.112 PM [0x0-0x5cb5cb].com.meeech.shopify_theme2: [04:09:48:111] [Titanium.API] [Information] PUT: Success
22/02/12 3:09:48.115 PM [0x0-0x5cb5cb].com.meeech.shopify_theme2: [04:09:48:114] [Titanium.Network.HTTPClient] [Error] Request to http://92e8b52399eaa95f14210fdb7abc8ec8:bf63c56b01b505431145d19226b72632@hugsandgiggles.myshopify.com/admin/themes/1807292/assets.json?asset[key]=assets%2Ftw%2Dwidget.js failed because: (JavaScript.KKJSObject) {}

## 

Stewart Johnson
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by stewartjohnson** [comment] 2012-03-20 13:28
Hi Mitchell -

Some more data. I'm having issues tonight using the shopify template editor -- details are here: http://forums.shopify.com/categories/2/posts/104917

I tried using your shopify sync tool and it hung when trying to download styles.css.liquid. I'm not sure if that's related to the previous issues I was having, but I figured it might be a useful data point.

Cheers,
Stewart

## 

Stewart Johnson
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by meeech** [comment] 2012-03-20 23:05
thanks stewart.

**Comment by meeech** [comment] 2012-03-25 19:47
update: I've found the cause of the bug. Fix will be in next release.

**Closed as completed** 2012-03-25 20:31 UTC
Labels: bug
